
# ----- Si desea agregar más preguntas debe cambiar el for i range (x) en donde x es la cantidad de preguntas ---
# ----- Ultima linea de codigo de pregunta - 4 = x ----
question = [
    ["¿Que hago si tengo problemas tecnicos con mi computador?","En este caso debes dirigirte al 10mo piso para solicitar soporte en la oficina"]
    ,["¿Como puedo solicitar un certificado laboral?","Debes ingresar a Success Factors, en tu perfil encontrarás un apartado llamado 'Información de Nómina', ahí se encuentran los enlaces para solicitar un certificado laboral y demás relacionados."]
    ,["¿Que tengo que hacer si dejo mi carné?","En caso de no contar con tu carné, deberás registrarte como visitante en la recepción de la sede, esto solo lo podrás hacer una vez por mes, si reincides, tu jefe inmediato deberá enviar un correo al analista de seguridad de la regional para autorizar tu ingreso en horario hábil."]
    ,["¿Que tengo que hacer si pierdo mi carné?","Tu carné es un elemento personal e intransferible, en caso de que se te pierda deberás poner el respectivo denuncio ante las entidades competentes y cancelar el valor correspondiente para su reposición, además de reportarlo a la Gerencia de Seguridad a través del correo carnetizacion@claro.com.co o a la extensión 80337."]
    ,["¿Como puedo solicitar una Sala de Reuniones?","Si requieres hacer uso de una sala de reuniones ubicada en los diferentes pisos de la sede, podrás realizar la reserva a través del calendario del correo electrónico Outlook u Office 365, en donde debes validar la disponibilidad de la sala de reunión a reservar, relacionar los asistentes, el tiempo de la reserva y darle enviar para que registre la citación y se guarde la reserva."]
    ,["¿Como puedo solicitar un espacio recreativo en la Terraza?","Puedes disfrutar de los espacios recreativos en tu hora de almuerzo o tiempo libre, incluso puedes hacer un BBQ con tu gerencia pero para ello ten las siguientes consideraciones: Las mesas de Ping Pong deberás escribirle por Teams a 'Zona Bienestar Terraza' preguntando por disponibilidad en el horario que desees, esta persona te guiará para poder apartarla. Para los Futbolitos podrás escribirle a 'Zona Bienestar Terraza' o ir a la oficina de Bienestar del 10mo piso, Las canchas de todo tipo deben ser apartadas con antelación y el dia de su uso deberás tener obligatoriamente vestimenta deportiva."]  
    ]