
# ----- Si desea agregar más preguntas debe cambiar el for i range (x) en donde x es la cantidad de preguntas ---
# ----- Ultima linea de codigo de pregunta - 4 = x ----
question = [
    ["1. ¿Que hago si tengo problemas tecnicos con mi computador?","En este caso debes dirigirte al 10mo piso para solicitar soporte en la oficina"]
    ,["2. ¿Como puedo solicitar un certificado laboral?","Respuesta2"]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]
    ,["",""]    
    ]